name: Test deploy # Workflow 이름
on: # Event 감지
  push:
    branches:
      - dev
jobs: # Job 설정
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout source code. # Repo checkout
        uses: actions/checkout@v2

      - name: Check Node v # Node v 확인
        run: node -v

      - name: Install Dependencies # 의존 파일 설치
        run: yarn install --frozen-lockfile

      - name: Build # React Build
        run: CI='false' yarn build

      - name: Deploy # Upload build file to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SECRET_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          CI: ""
        run: |
          aws s3 cp --recursive --region ap-northeast-2 build s3://www.the-goods.store

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }} # EC2 인스턴스의 호스트 주소
          username: ${{ secrets.EC2_USERNAME }} # EC2 인스턴스의 사용자 이름
          key: ${{ secrets.EC2_SSH_PRIVATE }} # SSH 비밀 키
          script: |
            rsync -avz -e "ssh -o StrictHostKeyChecking=no" build ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ubuntu/build/
