name: Test deploy # Workflow 이름
on: # Event 감지
  push:
    branches:
      - dev
jobs: # Job 설정
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code. # Repo checkout
        uses: actions/checkout@v2

      - name: Check Node v # Node v 확인
        run: node -v

      - name: Install Dependencies # 의존 파일 설치
        run: yarn install --frozen-lockfile

      - name: Build # React Build
        run: CI='false' yarn build

      - name: Build Docker Image
        run: docker build -t thegoods-front .

      - name: Export Docker Image
        run: docker save -o ec2.tar thegoods-front

      - name: Send to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }} # EC2 인스턴스의 호스트 주소
          username: ${{ secrets.EC2_USERNAME }} # EC2 인스턴스의 사용자 이름
          key: ${{ secrets.EC2_SSH_PRIVATE }} # SSH 비밀 키
          source: "./ec2.tar"
          target: "/home/ubuntu"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }} # EC2 인스턴스의 호스트 주소
          username: ${{ secrets.EC2_USERNAME }} # EC2 인스턴스의 사용자 이름
          key: ${{ secrets.EC2_SSH_PRIVATE }} # SSH 비밀 키
          script: |
            cd /home
            docker load -i ec2.tar
            docker run -d --name frontend -p 80:80 thegoods-front
