name: Test deploy # Workflow 이름
on: # Event 감지
  push:
    branches:
      - dev
jobs: # Job 설정
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code. # Repo checkout
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }} # EC2 인스턴스의 호스트 주소
          username: ${{ secrets.EC2_USERNAME }} # EC2 인스턴스의 사용자 이름
          key: ${{ secrets.EC2_SSH_PRIVATE }} # SSH 비밀 키
          script: |
            cd client
            git checkout dev
            git reset --hard
            git fetch
            git pull
            CI='false' yarn build
